version: '2'

services:
  mongodb:
    image: mongo

  frontend:
    image: nginx:1.15-alpine
    volumes:
      - /mnt/film-list/front-end/default.conf:/etc/nginx/conf.d/default.conf
      - /mnt/film-list/front-end/dist:/usr/share/nginx/html
    ports:
      - "5678:80"
    depends_on:
      - backend

  backend:
    image: hitoka/film-list-backend
    ports:
      - "5679:5000"
    depends_on:
      - mongodb

networks:
  default:
    external:
      name: film-list-network